spring: 
 profiles: 
  active:
   - dev

---
server: 
 port: 8201
spring: 
 profiles: dev
 application: 
   name: microservice-config-client
eureka: 
 client: 
  service-url: 
   defaultZone: http://crmEureka7001.com:7001/eureka/,http://crmEureka7002.com:7002/eureka/

---

server: 
 port: 8202
spring: 
 profiles: test
 application: 
   name: microservice-config-client
eureka: 
 client: 
  service-url: 
   defaultZone: http://crmEureka7001.com:7001/eureka/,http://crmEureka7002.com:7002/eureka/