spring: 
 profiles: 
  active:
   - dev

---

spring: 
 profiles: dev
 applicction: 
  name: microservice-config-aoao-dev

---

spring: 
 profiles: test
 applicction: 
  name: microservice-config-aoao-test
