spring: 
 profiles: 
  active:
   - dev
---
spring: 
 profiles: dev
 application: 
  name: microservice-config-aoao-dev
---
spring: 
 profiles: test
 application: 
  name: microservice-config-aoao-test
